# Backend server port
server.port=8081

# App name
spring.application.name=storage-health-api

# SQLite database path
# This points to the database created by your Python engine.
spring.datasource.url=jdbc:sqlite:D:/Smart Storage Health Monitor/engine/storage_health.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# SQLite does not need username/password
spring.datasource.username=
spring.datasource.password=

# Hibernate SQLite dialect
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Very important:
# Python already created the tables.
# Spring Boot should NOT create/drop/change them.
spring.jpa.hibernate.ddl-auto=none

# Show SQL queries in terminal while developing
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQLite is file-based, so keep DB connection pool small
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.connection-timeout=10000

# Better error messages during development
server.error.include-message=always
